# Generated by Django 4.2.6 on 2024-01-18 13:34

import data_tables.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activity_map", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "download_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "xlsx_file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_reports"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_reports"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_name",
                        to="reports.category",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_name",
                        to="reports.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("oblast", models.CharField(max_length=100)),
                ("benef", models.IntegerField()),
                ("activities", models.ManyToManyField(to="reports.category")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=data_tables.models.get_photo_path,
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("demography", models.JSONField(blank=True, null=True)),
                ("received_items", models.JSONField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_entries",
                        to="reports.category",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activity_map.place",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_entries",
                        to="reports.project",
                    ),
                ),
            ],
        ),
    ]
