# Generated by Django 4.2.6 on 2024-01-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_distr", "0002_manageraccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageraccess",
            name="regions",
            field=models.ManyToManyField(
                blank=True, to="search_distr.region", verbose_name="Regions"
            ),
        ),
    ]
