# Generated by Django 4.2.6 on 2024-02-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
        ("search_distr", "0003_alter_manageraccess_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.category",
            ),
        ),
    ]
