# Generated by Django 4.2.6 on 2024-01-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_distr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_full", models.BooleanField(default=False)),
                (
                    "regions",
                    models.ManyToManyField(
                        to="search_distr.region", verbose_name="Regions"
                    ),
                ),
            ],
        ),
    ]
