# Generated by Django 4.2.6 on 2024-01-29 10:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_point",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("start_odometer_kilometres", models.PositiveBigIntegerField()),
                (
                    "start_odometer_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="road_logistics/odometer/start/",
                    ),
                ),
                ("note_start", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "end_point",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("end_odometer_kilometres", models.PositiveBigIntegerField()),
                (
                    "end_odometer_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="road_logistics/odometer/end/"
                    ),
                ),
                ("note_end", models.CharField(blank=True, max_length=300, null=True)),
                ("is_refueling", models.BooleanField()),
                (
                    "refueling_check",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="road_logistics/checks/",
                    ),
                ),
                ("fuel_litre", models.IntegerField(blank=True, null=True)),
                ("mission", models.CharField(max_length=300)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="road_logistics.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RidePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="road_logistics.ride",
                    ),
                ),
            ],
        ),
    ]
