# Generated by Django 4.2.6 on 2024-01-25 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_user_type"),
        ("accounts", "0002_customuser_manager_access_alter_customuser_user_type"),
    ]

    operations = []
