# Generated by Django 5.0 on 2024-01-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
        ('accounts', '0003_merge_20240125_1326'),
    ]

    operations = [
    ]
