# Generated by Django 4.2.6 on 2024-01-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("search_distr", "0002_manageraccess"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="manager_access",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="search_distr.manageraccess",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("AD", "Admin"), ("DO", "Donor"), ("MA", "Manager")],
                default="DO",
                max_length=2,
            ),
        ),
    ]
