# Generated by Django 4.2.6 on 2024-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_manager_access_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("AD", "Admin"),
                    ("DO", "Donor"),
                    ("MA", "Manager"),
                    ("DR", "Driver"),
                ],
                default="DO",
                max_length=2,
            ),
        ),
    ]
